### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "batelgrill@gmail.com",
  "name": "Batel Grill",
  "cnpj": "20843769971323",
  "block": "1",
  "image": "batelgrill.jpg",
  "password": "@Livia040323"
}

### Sign in as an existing user
POST http://localhost:3000/auth2/signin
content-type: application/json

{
  "email": "ocostadallo@gmail.com",
  "password": "@Livia040323"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find all users
GET http://localhost:3000/auth/adm/users

### Find all restaurants
GET http://localhost:3000/auth/adm/restaurants

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com

### Delete a user given id
DELETE http://localhost:3000/auth/6

### Update a user
PATCH http://localhost:3000/auth/3
content-type: application/json

{
  "IsAdmin": true
}
