### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "otaviodallo@gmail.com",
  "name": "Otávio Dallo",
  "cpf": "10843769931",
  "password": "@Livia040323"
}

### Sign in as an existing user
POST http://localhost:3000/auth2/signin
content-type: application/json

{
  "email": "ocostadallo@gmail.com",
  "password": "@Livia040323"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find all users
GET http://localhost:3000/auth/adm/users

### Find all restaurants
GET http://localhost:3000/auth/adm/restaurants

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com

### Delete a user given id
DELETE http://localhost:3000/auth/1

### Update a user
PUT http://localhost:3000/auth/1 HTTP/1.1
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="email"

ocostadallo@gmail.com
--MfnBoundry
Content-Disposition: form-data; name="name"

Otávio Costa Dallo
--MfnBoundry
Content-Disposition: form-data; name="cpf"

10843769971
--MfnBoundry
Content-Disposition: form-data; name="image"; filename="eutmj.jfif"
Content-Type: image/jpeg

< eutmj.jfif
--MfnBoundry--

