### Create a product
POST http://localhost:3000/products
content-type: application/json

{
  "name": "Coca-Cola",
  "description": "Coca-cola gelada",
  "price": "4,50",
  "image": "coca-cola.jpg",
  "restaurant_id": 1
}

### Find all products
GET http://localhost:3000/products/

### Find one product
GET http://localhost:3000/products/2

### Delete a product
DELETE http://localhost:3000/products/4


### Update a product
PATCH http://localhost:3000/products/5
content-type: application/json

{
  "description": "Tubaina congelante"
}